### ISSUE TITLE
Add server reflection for gRPC

### ISSUE THREAD

**Issue by rohilsurana** [odpf/siren#143]
**Problem**
Unable to list services and methods supported when using tools like `grpcurl`.
This also allows tools to use the definitions provided by the reflection API for encoding request payloads without needing to supply the actual proto definitions.

**Solution**
Enable reflection API using the [reflection go package](https://pkg.go.dev/google.golang.org/grpc/reflection)

**Alternates**
Use the protobuf definitions available in [Proton](https://github.com/odpf/proton) for checking the supported methods.

**Comment by mabdh** [comment]
@rohilsurana reflection is implemented here https://github.com/odpf/siren/blob/main/internal/server/server.go#L104
maybe something wrong with that, let me check it

**Comment by rohilsurana** [comment]
Looks like there has been no release since this was added. Closing this for now and will use the next release when available.
