### ISSUE TITLE
Laundry list of improvements

### ISSUE THREAD

**Issue by whoAbhishekSah** [odpf/siren#38]
This is a running list of possible code improvements.
1. File naming convention in `api/handlers` directory. Some files are singular names and some are plural names. 
2. Router is bloated with all endpoints, can we namespace the routes in separate router files and include all of them in a top-level/top-tier router? 
3. Moving request validation from `handlers` to `domain` Example Commit: https://github.com/odpf/siren/commit/2ae3bce6aef8d8c79a2b3e5809465274a128d15a
4. Add test coverage info in readme

**Comment by whoAbhishekSah** [comment]
@pyadav  for your reference.

**Comment by ravisuhag** [comment]
@whoAbhishekSah FYI, We are thinking of moving to GRPC in an upcoming version.

**Comment by burntcarrot** [comment]
@whoAbhishekSah  I'd like to take this as I'm actively working on moving the request validation to `domain`. Could you assign me to this issue?

**Comment by ravisuhag** [comment]
This issue is covered as part of moving to GRPC.
