### ISSUE TITLE
Improve logs for /oauth/slack/token api

### ISSUE THREAD

**Issue by snorlacs** [odpf/siren#68]
**Problem:**
The logs for the `/oauth/slack/token` API  is not clear for the following scenarios.

- slack-credentials like `client_id` or `client_secret`  is wrong 
- the redirect oauth `code` is wrong

Siren logs looks like below [VERY HARD TO DEBUG]
`{"level":"error","ts":1635444416.7504508,"caller":"handlers/utils.go:30","msg":"handler","error":"failed to exchange code with slack OAuth server: slack oauth call failed","errorVerbose":"slack oauth call failed\ngithub.com/odpf/siren/pkg/codeexchange.(*SlackClient).Exchange\n\t/Users/dwarakeshvenkatasamy/workspace/siren/pkg/codeexchange/http.go:62\ngithub.com/odpf/siren/pkg/codeexchange.Service.Exchange\n\t/Users/dwarakeshvenkatasamy/workspace/siren/pkg/codeexchange/service.go:46\ngithub.com/odpf/siren/api/handlers.ExchangeCode.func1\n\t/Users/dwarakeshvenkatasamy/workspace/siren/api/handlers/codeexchange.go:20\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/purini-to/zapmw.Recoverer.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/purini-to/zapmw@v1.1.0/recoverer.go:33\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/purini-to/zapmw.Request.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/purini-to/zapmw@v1.1.0/request.go:37\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/purini-to/zapmw.WithZap.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/purini-to/zapmw@v1.1.0/context.go:27\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/newrelic/go-agent/v3/integrations/nrgorilla.Middleware.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/newrelic/go-agent/v3/integrations/nrgorilla@v1.1.0/nrgorilla.go:107\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1929\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nfailed to exchange code with slack OAuth server\ngithub.com/odpf/siren/pkg/codeexchange.Service.Exchange\n\t/Users/dwarakeshvenkatasamy/workspace/siren/pkg/codeexchange/service.go:49\ngithub.com/odpf/siren/api/handlers.ExchangeCode.func1\n\t/Users/dwarakeshvenkatasamy/workspace/siren/api/handlers/codeexchange.go:20\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/purini-to/zapmw.Recoverer.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/purini-to/zapmw@v1.1.0/recoverer.go:33\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/purini-to/zapmw.Request.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/purini-to/zapmw@v1.1.0/request.go:37\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/purini-to/zapmw.WithZap.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/purini-to/zapmw@v1.1.0/context.go:27\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/newrelic/go-agent/v3/integrations/nrgorilla.Middleware.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/newrelic/go-agent/v3/integrations/nrgorilla@v1.1.0/nrgorilla.go:107\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1929\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","stacktrace":"github.com/odpf/siren/api/handlers.internalServerError\n\t/Users/dwarakeshvenkatasamy/workspace/siren/api/handlers/utils.go:30\ngithub.com/odpf/siren/api/handlers.ExchangeCode.func1\n\t/Users/dwarakeshvenkatasamy/workspace/siren/api/handlers/codeexchange.go:23\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/purini-to/zapmw.Recoverer.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/purini-to/zapmw@v1.1.0/recoverer.go:33\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/purini-to/zapmw.Request.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/purini-to/zapmw@v1.1.0/request.go:37\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/purini-to/zapmw.WithZap.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/purini-to/zapmw@v1.1.0/context.go:27\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/newrelic/go-agent/v3/integrations/nrgorilla.Middleware.func1.1\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/newrelic/go-agent/v3/integrations/nrgorilla@v1.1.0/nrgorilla.go:107\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/Users/dwarakeshvenkatasamy/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1929"}`

**Potential Solution:**

In here https://github.com/odpf/siren/blob/main/pkg/codeexchange/http.go#L51
The unmarshal is causing the error to be lost as the schema for error will be like
`{"ok": false, "error": "invalid_code"}`

So print out the stringified version of `bodyBytes` if response is not `ok`

**Comment by mabdh** [comment]
We are improving the slack integration and would evaluate whether this still relevant or not later. If this is not relevant anymore (issue was solved), we will close this issue.
